select * from customer limit 20


--Q1. What is the total revenue generated by male vs female customer?

select gender, sum(Purchase_amount) as revenue
from customer
group by gender;

--Q2.Which customer used a discount but still spent mpre than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) From customer)

--Q3. which are the top 5 products with the hightest average review rating?

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

--Q4. Compare the average purchase amounts between standard and Express shopping.

select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subcribed customers spent more? Compare average spend and total revenue between subscribers and non-subcribers.

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc

--Q6 are customers who are repeat buyrs (more than 5 previous purchases) also likely to subcribe?

select subscription_status,
count(customer_id) as repeat_buyres
from customer
where previous_purchases >= 5
group by subscription_status


--Q7 what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc


